micronaut:
  application:
    name: pomodoroWayBackend
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:19006
            - http://localhost:8081
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

logger:
  levels:
    com.pomodorowork: INFO
